name: Deploy todo,
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18.x"
          registry-url: https://registry.npmjs.org
      - run: |
          version=$(echo ${GITHUB_REF##*/} | tr -d 'v')
          sed -i "s/\"\$version\"/\"$version\"/g" package.json
          cat package.json
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
